apiVersion: lightspeed.openstack.org/v1beta1
kind: OpenStackLightspeed
metadata:
  labels:
    app.kubernetes.io/name: openstack-lightspeed-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstacklightspeed-sample
spec:
  llmEndpoint: http://llm_provider:11434/v1
  llmEndpointType: openai
  llmCredentials: openstack-lightspeed-apitoken
  modelName: llama3.1:8b
  tlsCACertBundle: openstack-lightspeed-certs
